### ISSUE TITLE
Base creation of the sign-up page

### ISSUE THREAD

**Issue by dkbramble** [dkbramble/studique#12]
As a user, I will be able to interact with all of the basic elements on the sign-up page.

**Comment by davidjes97** [comment]
- [x] Create Initial folder and files

- [x] Create jsx components and email and password input fields

- [x] Create sign-up button

- [x] Create sign-up w/Google Button

- [x] Format using css

- [ ]  Add Display name input field

- [ ] Select Student or Faculty

**Comment by davidjes97** [comment]
This will be more of a base sign-up and sign-in popups.
